### PR TITLE
TERA-11088 Changing SqlContext to SparkSession

### PR DESCRIPTION
**Pull request by autumnderr**

### CODE REVIEW

**Comment by clarify-ankush** [comment]
@autumnderr I am going to review this today but please don't merge it.. Merging to master will replace the current production version so we will need to co-ordinate with teradrome changes going in master and other releases like ccg/stp unless we update the jar version everywhere like in code and steps etc https://github.com/clarifyhealth/tera_catalog/blob/19a35d4ae437796aee9648879e09bf0a8e191f9e/emr/base-steps.json#L31

**Review by roman-y — APPROVED** [review]

**Review by poolis — APPROVED** [review]

**Review by clarify-ankush — APPROVED** [review]
The PR looks good to me, but lets figure out the plan to merge/deploy in production. It would be good to test out these changes in prod by publishing a different version 0.3 manually and run some pipelines to make sure none of the changes are breaking changes.

**Comment by autumnderr** [comment]
> 

Okay! Here's the teradrome PR that uses these changes: https://github.com/clarifyhealth/teradrome/pull/6817. I added the 0.2 jar file into the folder and set conftest to the new 0.2 file. Would that be fine for production or are there more steps needed before merging this?

**Comment by clarify-ankush** [comment]
@autumnderr it does not have to be 0.3 but if you want to test before merging we can change to 0.3 and test

**Pull request merged**
